const constants = {
  FETCH_REPOS: 'FETCH_REPOS',
  MAP_ISSUES_TO_REPO: 'MAP_ISSUES_TO_REPO',
  CLEAR_REPOS: 'CLEAR_REPOS',
  REORDER_ISSUES: 'REORDER_ISSUES',
  CLEAR_ISSUES: 'CLEAR_ISSUES',
  SET_KEY: 'SET_KEY',
  CLEAR_KEY: 'CLEAR_KEY',
  SELECT_REPO: 'SELECT_REPO'
}

export default constants
